// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  catalog_home: dynamic(() => import("./CatalogHome")),
  contacts: dynamic(() => import("./Contacts")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  works: dynamic(() => import("./Works")),
};
